FROM alpine:3.20

RUN apk add --no-cache ca-certificates git && \
    adduser -D -h /home/leakwatch leakwatch

COPY leakwatch /usr/local/bin/leakwatch

USER leakwatch
WORKDIR /scan

ENTRYPOINT ["leakwatch"]
CMD ["--help"]
